version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
         red_interna:
             ipv4_address: ${IPV4_MYSQL}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_server
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
         red_interna:
             ipv4_address: ${IPV4_PHPMYADMIN}
networks:
     red_interna:
         ipam:
             config:
             - subnet: ${NET_SUBNET}
